# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest ./ --doctest-modules --junitxml=junit/test-results.xml --cov=./ --cov-report=xml --cov-report=html --cov-config=.coveragerc
    - name: Generate coverage badge with codecov
      if: always()
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
    - name: Run autopep8
      run: |
        pip install autopep8
        autopep8 --in-place --aggressive --aggressive HW2/src/*.py > HW2/latest_logging/autopep8_logging 
    - name: Run pylint
      run: |
        pip install pylint
        pylint HW2/src > HW2/latest_logging/pylint_logging


